In [2]:
# Importaçoes
import pandas as pd
import plotly.express as px

# OBS: caso usar pelo google
# excel: google sheet     dica de extençao: sheetgpt
# vscode: google colab

In [3]:
# --- ler tabelas
df_principal = pd.read_excel("tabela.xlsx" , sheet_name="Principal") # sheet_name selecionar aba do excel
df_principal.head(10) # mostra o intervalo de linhas, sem o head um mostra geral

,Ativo,Data,Último (R$),Var. Dia (%),Var. Sem. (%),Var. Mês (%),Var. Ano (%),Var. 12M (%),Val. Mín,Val. Máx,Volume,Variaçao %,Valor inicial R$,total de acesso,variaçao $,Resultado,nome da empresa,segmentos,Idade,Faixa etaria
0,USIM5,2024-01-26,9.50,5.20,11.76,2.26,2.26,15.97,9.18,9.56,"319,16 M",0.0520,9.030418,515117391,2.418897e+08,Subiu,Usiminas,Siderurgia,50,Entre 50 a 100
1,CMIN3,2024-01-26,6.82,2.40,2.40,-12.11,-12.11,50.56,6.66,6.86,"32,65 M",0.0240,6.660156,1110559345,1.775160e+08,Subiu,CSN Mineração,Mineração,45,Menor de 50
2,PETR3,2024-01-26,41.96,2.19,7.73,7.64,7.64,77.55,40.81,42.34,"436,69 M",0.0219,41.060769,2379877655,2.140059e+09,Subiu,Petrobras,Petróleo e Gás,67,Entre 50 a 100
3,SUZB3,2024-01-26,52.91,2.04,2.14,-4.89,-4.89,18.85,51.89,53.17,"162,55 M",0.0204,51.852215,683452836,7.229463e+08,Subiu,Suzano,Papel e Celulose,30,Menor de 50
4,CPFE3,2024-01-26,37.10,2.03,2.49,-3.66,-3.66,20.70,36.37,37.32,"73,42 M",0.0203,36.361854,187732538,1.385740e+08,Subiu,CPFL Energia,Energia Elétrica,28,Menor de 50
5,PRIO3,2024-01-26,45.69,1.98,2.42,-0.78,-0.78,8.08,44.25,45.69,"319,92 M",0.0198,44.802903,800010734,7.096875e+08,Subiu,PetroRio,Petróleo e Gás,22,Menor de 50
6,PETR4,2024-01-26,39.96,1.73,6.47,7.30,7.30,95.01,38.91,40.09,"1,64 B",0.0173,39.280448,4566445852,3.103136e+09,Subiu,Petrobras,Petróleo e Gás,67,Entre 50 a 100
7,VALE3,2024-01-26,69.50,1.66,2.06,-9.97,-9.97,-23.49,67.50,69.81,"1,89 B",0.0166,68.365139,4196924316,4.762927e+09,Subiu,Vale,Mineração,60,Entre 50 a 100
8,MULT3,2024-01-26,28.19,1.58,2.03,-0.81,-0.81,24.02,27.71,28.36,"104,16 M",0.0158,27.751526,268505432,1.177327e+08,Subiu,Multiplan,Shopping Centers,36,Menor de 50
9,ITUB4,2024-01-26,32.81,1.48,-0.39,-3.36,-3.36,34.25,32.35,32.91,"473,2 M",0.0148,32.331494,4801593832,2.297592e+09,Subiu,Itaú Unibanco,Instituição Financeira,80,Entre 50 a 100

In [4]:
df_total_de_acoes = pd.read_excel("tabela.xlsx" , sheet_name="Total_de_acoes")
df_total_de_acoes.head()

  Código  Qtde. Teórica
0  RRRP3   2.356656e+08
1  ALOS3   5.326166e+08
2  ALPA4   1.767340e+08
3  ABEV3   4.394246e+09
4  ARZZ3   6.230589e+07

In [5]:
df_Ticker = pd.read_excel("tabela.xlsx" , sheet_name="Ticker")
df_Ticker.head()

  Ticker            Nome
0  MGLU3  Magazine Luiza
1  HAPV3         Hapvida
2  PETR4       Petrobras
3  B3SA3              B3
4  USIM5        Usiminas

In [6]:
df_Chat_GPT = pd.read_excel("tabela.xlsx" , sheet_name="Chat_GPT")
df_Chat_GPT

             Empresa           Segmento  Idade
0           Usiminas         Siderurgia     50
1      CSN Mineração          Mineração     45
2          Petrobras     Petróleo e Gás     67
3             Suzano   Papel e Celulose     30
4       CPFL Energia   Energia Elétrica     28
..               ...                ...    ...
73  Carrefour Brasil             Varejo    234
74       Casas Bahia             Varejo     22
75          Localiza  Aluguel de Carros     34
76               CVC            Turismo    223
77               GOL   Transporte Aéreo     55

[78 rows x 3 columns]

In [7]:
# filtras colunas de uso
df_principal = df_principal[["Ativo", "Data", "Último (R$)","Var. Dia (%)"]].copy() # copiar tabelas/ redefinir 
df_principal

    Ativo       Data  Último (R$)  Var. Dia (%)
0   USIM5 2024-01-26         9.50          5.20
1   CMIN3 2024-01-26         6.82          2.40
2   PETR3 2024-01-26        41.96          2.19
3   SUZB3 2024-01-26        52.91          2.04
4   CPFE3 2024-01-26        37.10          2.03
..    ...        ...          ...           ...
76  CRFB3 2024-01-26        10.71         -2.45
77  BHIA3 2024-01-26         8.70         -2.46
78  RENT3 2024-01-26        56.24         -3.63
79  CVCB3 2024-01-26         3.07         -4.36
80  GOLL4 2024-01-26         5.92         -8.07

[81 rows x 4 columns]

In [8]:
# redefinindo nome das colunas/ evitar erro
df_principal = df_principal.rename(columns= {"Último (R$)": "valor_final", "Var. Dia (%)" : "var_dia_pct"}).copy() # renomear colunas { "nome atual" : "novo nome" }
df_principal

    Ativo       Data  valor_final  var_dia_pct
0   USIM5 2024-01-26         9.50         5.20
1   CMIN3 2024-01-26         6.82         2.40
2   PETR3 2024-01-26        41.96         2.19
3   SUZB3 2024-01-26        52.91         2.04
4   CPFE3 2024-01-26        37.10         2.03
..    ...        ...          ...          ...
76  CRFB3 2024-01-26        10.71        -2.45
77  BHIA3 2024-01-26         8.70        -2.46
78  RENT3 2024-01-26        56.24        -3.63
79  CVCB3 2024-01-26         3.07        -4.36
80  GOLL4 2024-01-26         5.92        -8.07

[81 rows x 4 columns]

In [9]:
# Criar nova coluna, pegando a anterios e dividindo 100
df_principal["Var_pct"] = df_principal["var_dia_pct"]/100
# Criando nova coluna para o valor inicial 
df_principal["valor_inicial"] = df_principal["valor_final"] /(1+ df_principal["Var_pct"])
df_principal

    Ativo       Data  valor_final  var_dia_pct  Var_pct  valor_inicial
0   USIM5 2024-01-26         9.50         5.20   0.0520       9.030418
1   CMIN3 2024-01-26         6.82         2.40   0.0240       6.660156
2   PETR3 2024-01-26        41.96         2.19   0.0219      41.060769
3   SUZB3 2024-01-26        52.91         2.04   0.0204      51.852215
4   CPFE3 2024-01-26        37.10         2.03   0.0203      36.361854
..    ...        ...          ...          ...      ...            ...
76  CRFB3 2024-01-26        10.71        -2.45  -0.0245      10.978985
77  BHIA3 2024-01-26         8.70        -2.46  -0.0246       8.919418
78  RENT3 2024-01-26        56.24        -3.63  -0.0363      58.358410
79  CVCB3 2024-01-26         3.07        -4.36  -0.0436       3.209954
80  GOLL4 2024-01-26         5.92        -8.07  -0.0807       6.439682

[81 rows x 6 columns]

In [10]:
# merge = procv
# merge(nome_tabela_onde_procurar, left_on = "nome da coluna onde queremos associar", 
# ... right_on=" nome da coluna na tabela onde procurar, how= "lef or right, usar para preencher qual")
df_principal = df_principal.merge(df_total_de_acoes, left_on= "Ativo",right_on= "Código", how = "left")
df_principal
#OBS, ele ira associar mas trara a coluna rigth junto, necessitando dropar para nao repetir info

# Renomear "Qtde. Teórica"
df_principal = df_principal.rename(columns= {"Qtde. Teórica": "quantidade_teorica"}).copy()

In [11]:
# drop = apagar 
df_principal = df_principal.drop(columns= ["Código"])
df_principal

,Ativo,Data,valor_final,var_dia_pct,Var_pct,valor_inicial,quantidade_teorica
0,USIM5,2024-01-26,9.50,5.20,0.0520,9.030418,5.151174e+08
1,CMIN3,2024-01-26,6.82,2.40,0.0240,6.660156,1.110559e+09
2,PETR3,2024-01-26,41.96,2.19,0.0219,41.060769,2.379878e+09
3,SUZB3,2024-01-26,52.91,2.04,0.0204,51.852215,6.834528e+08
4,CPFE3,2024-01-26,37.10,2.03,0.0203,36.361854,1.877325e+08
...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-2.45,-0.0245,10.978985,5.339906e+08
77,BHIA3,2024-01-26,8.70,-2.46,-0.0246,8.919418,9.484305e+07
78,RENT3,2024-01-26,56.24,-3.63,-0.0363,58.358410,8.532023e+08
79,CVCB3,2024-01-26,3.07,-4.36,-0.0436,3.209954,5.255828e+08
80,GOLL4,2024-01-26,5.92,-8.07,-0.0807,6.439682,1.981849e+08

In [12]:
# coluna variaçao

df_principal["variacao"] = (df_principal["valor_final"] - df_principal["valor_inicial"]) * df_principal["quantidade_teorica"]

df_principal

,Ativo,Data,valor_final,var_dia_pct,Var_pct,valor_inicial,quantidade_teorica,variacao
0,USIM5,2024-01-26,9.50,5.20,0.0520,9.030418,5.151174e+08,2.418897e+08
1,CMIN3,2024-01-26,6.82,2.40,0.0240,6.660156,1.110559e+09,1.775160e+08
2,PETR3,2024-01-26,41.96,2.19,0.0219,41.060769,2.379878e+09,2.140059e+09
3,SUZB3,2024-01-26,52.91,2.04,0.0204,51.852215,6.834528e+08,7.229463e+08
4,CPFE3,2024-01-26,37.10,2.03,0.0203,36.361854,1.877325e+08,1.385740e+08
...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-2.45,-0.0245,10.978985,5.339906e+08,-1.436355e+08
77,BHIA3,2024-01-26,8.70,-2.46,-0.0246,8.919418,9.484305e+07,-2.081024e+07
78,RENT3,2024-01-26,56.24,-3.63,-0.0363,58.358410,8.532023e+08,-1.807433e+09
79,CVCB3,2024-01-26,3.07,-4.36,-0.0436,3.209954,5.255828e+08,-7.355741e+07
80,GOLL4,2024-01-26,5.92,-8.07,-0.0807,6.439682,1.981849e+08,-1.029932e+08

In [13]:
# formatar numeros float, sumir com notaçao cientifica
pd.options.display.float_format= "{:.2f}".format
df_principal

,Ativo,Data,valor_final,var_dia_pct,Var_pct,valor_inicial,quantidade_teorica,variacao
0,USIM5,2024-01-26,9.50,5.20,0.05,9.03,515117391.00,241889725.43
1,CMIN3,2024-01-26,6.82,2.40,0.02,6.66,1110559345.00,177515970.30
2,PETR3,2024-01-26,41.96,2.19,0.02,41.06,2379877655.00,2140059393.53
3,SUZB3,2024-01-26,52.91,2.04,0.02,51.85,683452836.00,722946282.71
4,CPFE3,2024-01-26,37.10,2.03,0.02,36.36,187732538.00,138573955.06
...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-2.45,-0.02,10.98,533990587.00,-143635530.57
77,BHIA3,2024-01-26,8.70,-2.46,-0.02,8.92,94843047.00,-20810240.84
78,RENT3,2024-01-26,56.24,-3.63,-0.04,58.36,853202347.00,-1807432634.46
79,CVCB3,2024-01-26,3.07,-4.36,-0.04,3.21,525582771.00,-73557408.06
80,GOLL4,2024-01-26,5.92,-8.07,-0.08,6.44,198184909.00,-102993202.62

In [14]:
# converter "Qtde. Teórica" para int 
df_principal["quantidade_teorica"] = df_principal["quantidade_teorica"].astype(int)
df_principal

,Ativo,Data,valor_final,var_dia_pct,Var_pct,valor_inicial,quantidade_teorica,variacao
0,USIM5,2024-01-26,9.50,5.20,0.05,9.03,515117391,241889725.43
1,CMIN3,2024-01-26,6.82,2.40,0.02,6.66,1110559345,177515970.30
2,PETR3,2024-01-26,41.96,2.19,0.02,41.06,-2147483648,2140059393.53
3,SUZB3,2024-01-26,52.91,2.04,0.02,51.85,683452836,722946282.71
4,CPFE3,2024-01-26,37.10,2.03,0.02,36.36,187732538,138573955.06
...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-2.45,-0.02,10.98,533990587,-143635530.57
77,BHIA3,2024-01-26,8.70,-2.46,-0.02,8.92,94843047,-20810240.84
78,RENT3,2024-01-26,56.24,-3.63,-0.04,58.36,853202347,-1807432634.46
79,CVCB3,2024-01-26,3.07,-4.36,-0.04,3.21,525582771,-73557408.06
80,GOLL4,2024-01-26,5.92,-8.07,-0.08,6.44,198184909,-102993202.62

In [15]:
# cria coluna subiu pu desceu
# apply, funçao para aplicar outras funçoes, lambda: aplicar em todas linhas
df_principal["Resultado"] = df_principal["variacao"].apply(lambda x:"Subiu" if x>0 else ("Desceu" if x< 0 else "Estavel"))

df_principal

,Ativo,Data,valor_final,var_dia_pct,Var_pct,valor_inicial,quantidade_teorica,variacao,Resultado
0,USIM5,2024-01-26,9.50,5.20,0.05,9.03,515117391,241889725.43,Subiu
1,CMIN3,2024-01-26,6.82,2.40,0.02,6.66,1110559345,177515970.30,Subiu
2,PETR3,2024-01-26,41.96,2.19,0.02,41.06,-2147483648,2140059393.53,Subiu
3,SUZB3,2024-01-26,52.91,2.04,0.02,51.85,683452836,722946282.71,Subiu
4,CPFE3,2024-01-26,37.10,2.03,0.02,36.36,187732538,138573955.06,Subiu
...,...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-2.45,-0.02,10.98,533990587,-143635530.57,Desceu
77,BHIA3,2024-01-26,8.70,-2.46,-0.02,8.92,94843047,-20810240.84,Desceu
78,RENT3,2024-01-26,56.24,-3.63,-0.04,58.36,853202347,-1807432634.46,Desceu
79,CVCB3,2024-01-26,3.07,-4.36,-0.04,3.21,525582771,-73557408.06,Desceu
80,GOLL4,2024-01-26,5.92,-8.07,-0.08,6.44,198184909,-102993202.62,Desceu

In [16]:
# procV nome ,segmento e idade 

df_principal = df_principal.merge(df_Ticker, left_on="Ativo", right_on="Ticker", how= "left")

df_principal = df_principal.merge(df_Chat_GPT, left_on= "Nome",right_on= "Empresa", how = "left")

df_principal

,Ativo,Data,valor_final,var_dia_pct,Var_pct,valor_inicial,quantidade_teorica,variacao,Resultado,Ticker,Nome,Empresa,Segmento,Idade
0,USIM5,2024-01-26,9.50,5.20,0.05,9.03,515117391,241889725.43,Subiu,USIM5,Usiminas,Usiminas,Siderurgia,50
1,CMIN3,2024-01-26,6.82,2.40,0.02,6.66,1110559345,177515970.30,Subiu,CMIN3,CSN Mineração,CSN Mineração,Mineração,45
2,PETR3,2024-01-26,41.96,2.19,0.02,41.06,-2147483648,2140059393.53,Subiu,PETR3,Petrobras,Petrobras,Petróleo e Gás,67
3,SUZB3,2024-01-26,52.91,2.04,0.02,51.85,683452836,722946282.71,Subiu,SUZB3,Suzano,Suzano,Papel e Celulose,30
4,CPFE3,2024-01-26,37.10,2.03,0.02,36.36,187732538,138573955.06,Subiu,CPFE3,CPFL Energia,CPFL Energia,Energia Elétrica,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-2.45,-0.02,10.98,533990587,-143635530.57,Desceu,CRFB3,Carrefour Brasil,Carrefour Brasil,Varejo,234
77,BHIA3,2024-01-26,8.70,-2.46,-0.02,8.92,94843047,-20810240.84,Desceu,BHIA3,Casas Bahia,Casas Bahia,Varejo,22
78,RENT3,2024-01-26,56.24,-3.63,-0.04,58.36,853202347,-1807432634.46,Desceu,RENT3,Localiza,Localiza,Aluguel de Carros,34
79,CVCB3,2024-01-26,3.07,-4.36,-0.04,3.21,525582771,-73557408.06,Desceu,CVCB3,CVC,CVC,Turismo,223
80,GOLL4,2024-01-26,5.92,-8.07,-0.08,6.44,198184909,-102993202.62,Desceu,GOLL4,GOL,GOL,Transporte Aéreo,55

In [ ]:
df_principal["Faixa etaria"] = df_principal["Idade"].apply(lambda x:"maior que 100" if x > 100 else ("menor que 50" if x < 50 else "entre 50 a 100"))
df_principal

,Ativo,Data,valor_final,var_dia_pct,Var_pct,valor_inicial,quantidade_teorica,variacao,Resultado,Empresa,Segmento,Idade,Faixa etaria
0,USIM5,2024-01-26,9.50,5.20,0.05,9.03,515117391,241889725.43,Subiu,Usiminas,Siderurgia,50,entre 50 a 100
1,CMIN3,2024-01-26,6.82,2.40,0.02,6.66,1110559345,177515970.30,Subiu,CSN Mineração,Mineração,45,menor que 50
2,PETR3,2024-01-26,41.96,2.19,0.02,41.06,-2147483648,2140059393.53,Subiu,Petrobras,Petróleo e Gás,67,entre 50 a 100
3,SUZB3,2024-01-26,52.91,2.04,0.02,51.85,683452836,722946282.71,Subiu,Suzano,Papel e Celulose,30,menor que 50
4,CPFE3,2024-01-26,37.10,2.03,0.02,36.36,187732538,138573955.06,Subiu,CPFL Energia,Energia Elétrica,28,menor que 50
...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,CRFB3,2024-01-26,10.71,-2.45,-0.02,10.98,533990587,-143635530.57,Desceu,Carrefour Brasil,Varejo,234,maior que 100
77,BHIA3,2024-01-26,8.70,-2.46,-0.02,8.92,94843047,-20810240.84,Desceu,Casas Bahia,Varejo,22,menor que 50
78,RENT3,2024-01-26,56.24,-3.63,-0.04,58.36,853202347,-1807432634.46,Desceu,Localiza,Aluguel de Carros,34,menor que 50
79,CVCB3,2024-01-26,3.07,-4.36,-0.04,3.21,525582771,-73557408.06,Desceu,CVC,Turismo,223,maior que 100
80,GOLL4,2024-01-26,5.92,-8.07,-0.08,6.44,198184909,-102993202.62,Desceu,GOL,Transporte Aéreo,55,entre 50 a 100

In [ ]:
# ----------------- Ánalises -------------------------------

maior = df_principal["variacao"].max()

menor = df_principal["variacao"].min()

media = df_principal["variacao"].mean()

media_subiu = df_principal[df_principal["Resultado"]== "Subiu"]["variacao"].mean()

media_desceu = df_principal[df_principal["Resultado"]== "Desceu"]["variacao"].mean()

print(f"Maior \t{maior:,.2f}")
print(f"menor \t{menor:,.2f}")
print(f"media \t{media:,.2f}")
print(f"media_subiu \t{media_subiu:,.2f}")
print(f"media_desceu \t{media_desceu:,.2f}")

Maior 	4,762,926,995.25
menor 	-1,807,432,634.46
media 	165,190,210.48
media_subiu 	448,164,250.23
media_desceu 	-181,109,141.75

In [ ]:
# criaçao new df com apenas dados que subiram 

df_principal_subiu = df_principal[df_principal["Resultado"]== "Subiu"]
df_principal_subiu

,Ativo,Data,valor_final,var_dia_pct,Var_pct,valor_inicial,quantidade_teorica,variacao,Resultado,Ticker,Nome,Empresa,Segmento,Idade
0,USIM5,2024-01-26,9.50,5.20,0.05,9.03,515117391,241889725.43,Subiu,USIM5,Usiminas,Usiminas,Siderurgia,50
1,CMIN3,2024-01-26,6.82,2.40,0.02,6.66,1110559345,177515970.30,Subiu,CMIN3,CSN Mineração,CSN Mineração,Mineração,45
2,PETR3,2024-01-26,41.96,2.19,0.02,41.06,-2147483648,2140059393.53,Subiu,PETR3,Petrobras,Petrobras,Petróleo e Gás,67
3,SUZB3,2024-01-26,52.91,2.04,0.02,51.85,683452836,722946282.71,Subiu,SUZB3,Suzano,Suzano,Papel e Celulose,30
4,CPFE3,2024-01-26,37.10,2.03,0.02,36.36,187732538,138573955.06,Subiu,CPFE3,CPFL Energia,CPFL Energia,Energia Elétrica,28
5,PRIO3,2024-01-26,45.69,1.98,0.02,44.80,800010734,709687498.18,Subiu,PRIO3,PetroRio,PetroRio,Petróleo e Gás,22
6,PETR4,2024-01-26,39.96,1.73,0.02,39.28,-2147483648,3103136291.22,Subiu,PETR4,Petrobras,Petrobras,Petróleo e Gás,67
7,VALE3,2024-01-26,69.50,1.66,0.02,68.37,-2147483648,4762926995.25,Subiu,VALE3,Vale,Vale,Mineração,60
8,MULT3,2024-01-26,28.19,1.58,0.02,27.75,268505432,117732680.08,Subiu,MULT3,Multiplan,Multiplan,Shopping Centers,36
9,ITUB4,2024-01-26,32.81,1.48,0.01,32.33,-2147483648,2297591984.33,Subiu,ITUB4,Itaú Unibanco,Itaú Unibanco,Instituição Financeira,80
10,RDOR3,2024-01-26,27.56,1.43,0.01,27.17,1168230366,453917907.01,Subiu,RDOR3,Rede D'Or,Rede D'Or,Saúde,15
11,BRKM5,2024-01-26,18.55,1.42,0.01,18.29,265877867,69054317.64,Subiu,BRKM5,Braskem,Braskem,Petroquímica,38
12,AZUL4,2024-01-26,14.27,1.42,0.01,14.07,327593725,65452205.55,Subiu,AZUL4,Azul,Azul,Transporte Aéreo,20
13,RRRP3,2024-01-26,28.75,1.41,0.01,28.35,235665566,94204643.35,Subiu,RRRP3,3R Petroleum,3R Petroleum,Petróleo e Gás,25
14,EQTL3,2024-01-26,35.32,1.34,0.01,34.85,1095587251,511671895.45,Subiu,EQTL3,Equatorial Energia,Equatorial Energia,Energia Elétrica,32
15,CSNA3,2024-01-26,18.16,1.33,0.01,17.92,600865451,143220991.46,Subiu,CSNA3,Siderúrgica Nacional,Siderúrgica Nacional,Siderurgia,55
16,YDUQ3,2024-01-26,19.77,1.28,0.01,19.52,289347914,72295838.99,Subiu,YDUQ3,YDUQS,YDUQS,Educação,18
17,UGPA3,2024-01-26,28.31,1.28,0.01,27.95,1086411192,388705223.96,Subiu,UGPA3,Ultrapar,Ultrapar,Distribuição,40
18,MRVE3,2024-01-26,8.08,1.25,0.01,7.98,376187582,37525872.38,Subiu,MRVE3,MRV,MRV,Construção Civil,42
19,ARZZ3,2024-01-26,57.91,1.15,0.01,57.25,62305891,41021792.09,Subiu,ARZZ3,Arezzo,Arezzo,Calçados,24
20,BBDC4,2024-01-26,15.52,1.04,0.01,15.36,-2147483648,822148336.41,Subiu,BBDC4,Banco Bradesco,Banco Bradesco,Instituição Financeira,75
21,BEEF3,2024-01-26,7.19,0.98,0.01,7.12,261036182,18214628.10,Subiu,BEEF3,Minerva,Minerva,Alimentos,35
22,PCAR3,2024-01-26,4.14,0.97,0.01,4.10,159430826,6340916.22,Subiu,PCAR3,Grupo Pão de Açúcar,Grupo Pão de Açúcar,Alimentos e Varejo,70
23,BRFS3,2024-01-26,14.61,0.96,0.01,14.47,1677525446,233045769.57,Subiu,BRFS3,BRF,BRF,Alimentos,17
24,VIVT3,2024-01-26,51.20,0.88,0.01,50.75,423091712,188965307.06,Subiu,VIVT3,Vivo,Vivo,Telecomunicações,55
25,RAIL3,2024-01-26,22.64,0.84,0.01,22.45,1218352541,229771333.63,Subiu,RAIL3,Rumo,Rumo,Logística,48
26,CIEL3,2024-01-26,4.90,0.82,0.01,4.86,1095462329,43657683.38,Subiu,CIEL3,Cielo,Cielo,Serviços Financeiros,43
27,DXCO3,2024-01-26,7.81,0.77,0.01,7.75,302768240,18068446.61,Subiu,DXCO3,Dexco,Dexco,Serviços Diversos,27
28,TIMS3,2024-01-26,17.52,0.74,0.01,17.39,807896814,103972807.37,Subiu,TIMS3,TIM,TIM,Telecomunicações,53
29,BRAP4,2024-01-26,23.22,0.73,0.01,23.05,251003438,42238249.54,Subiu,BRAP4,Bradespar,Bradespar,Holding,68
30,LWSA3,2024-01-26,5.55,0.72,0.01,5.51,393173139,15598886.65,Subiu,LWSA3,Locaweb,Locaweb,Tecnologia,23
31,RECV3,2024-01-26,23.83,0.71,0.01,23.66,275005663,46201006.00,Subiu,RECV3,PetroRecôncavo,PetroRecôncavo,Petróleo e Gás,29
32,ITSA4,2024-01-26,10.01,0.70,0.01,9.94,-2147483648,373853994.88,Subiu,ITSA4,Itaúsa,Itaúsa,Holding,72
33,BBAS3,2024-01-26,56.97,0.68,0.01,56.59,1420949112,546752087.99,Subiu,BBAS3,Banco do Brasil,Banco do Brasil,Instituição Financeira,78
34,RADL3,2024-01-26,26.16,0.61,0.01,26.00,1275798515,202352473.74,Subiu,RADL3,RaiaDrogasil,RaiaDrogasil,Farmácias,33
35,GOAU4,2024-01-26,10.08,0.59,0.01,10.02,660411219,39045606.94,Subiu,GOAU4,Metalúrgica Gerdau,Metalúrgica Gerdau,Siderurgia,58
36,CSAN3,2024-01-26,18.57,0.59,0.01,18.46,1168097881,127229653.18,Subiu,CSAN3,Cosan,Cosan,Energia e Logística,37
37,JBSS3,2024-01-26,24.34,0.57,0.01,24.20,1134986472,156573285.43,Subiu,JBSS3,JBS,JBS,Alimentos,47
38,MGLU3,2024-01-26,2.08,0.48,0.00,2.07,-2147483648,28493619.27,Subiu,MGLU3,Magazine Luiza,Magazine Luiza,Varejo,31
39,BBDC3,2024-01-26,13.75,0.36,0.00,13.70,1500728902,74019610.05,Subiu,BBDC3,Banco Bradesco,Banco Bradesco,Instituição Financeira,75
40,GGBR4,2024-01-26,21.84,0.27,0.00,21.78,1118525506,65779607.10,Subiu,GGBR4,Gerdau,Gerdau,Siderurgia,60
41,RAIZ4,2024-01-26,3.74,0.26,0.00,3.73,1193047233,11571106.42,Subiu,RAIZ4,Raízen,Raízen,Energia,41
42,CPLE6,2024-01-26,10.07,0.19,0.00,10.05,1679335290,32069789.50,Subiu,CPLE6,Copel,Copel,Energia Elétrica,49
43,VAMO3,2024-01-26,8.18,0.12,0.00,8.17,421383330,4131341.16,Subiu,VAMO3,Grupo Vamos,Grupo Vamos,Transporte e Logística,34

In [ ]:
# criando df analise segmeto, baseado no df anterior, porem agrupando todos os do mesmo segmento e somando

df_analise_segmento = df_principal_subiu.groupby("Segmento")["variacao"].sum().reset_index() # reset para continuar como dataFrame
df_analise_segmento

                  Segmento      variacao
0                Alimentos  407833683.09
1       Alimentos e Varejo    6340916.22
2                 Calçados   41021792.09
3         Construção Civil   37525872.38
4             Distribuição  388705223.96
5                 Educação   72295838.99
6                  Energia   11571106.42
7         Energia Elétrica  682315640.01
8      Energia e Logística  127229653.18
9                Farmácias  202352473.74
10                 Holding  416092244.42
11  Instituição Financeira 3740512018.78
12               Logística  229771333.63
13               Mineração 4940442965.55
14        Papel e Celulose  722946282.71
15            Petroquímica   69054317.64
16          Petróleo e Gás 6093288832.26
17                   Saúde  453917907.01
18       Serviços Diversos   18068446.61
19    Serviços Financeiros   43657683.38
20        Shopping Centers  117732680.08
21              Siderurgia  489935930.93
22              Tecnologia   15598886.65
23        Telecomunicações  292938114.42
24        Transporte Aéreo   65452205.55
25  Transporte e Logística    4131341.16
26                  Varejo   28493619.27

In [19]:
df_analise_saldo = df_principal.groupby("Resultado")["variacao"].sum().reset_index() # reset para continuar como dataFrame
df_analise_saldo

  Resultado       variacao
0    Desceu -6338819961.32
1   Estavel           0.00
2     Subiu 19719227010.14

In [20]:
# graficos
# variavel = px.TipoDoGrafico(tabela, x do grafico, y do grafico, mostrar num do y, titulo do grafico)
fig = px.bar(df_analise_saldo, x="Resultado",y="variacao", text="variacao", title="Valor reais por resultado")
fig.show()